services:
  asynqmon:
    image: hibiken/asynqmon
    # TODO remove this once asynqmon publishes arm64 image
    platform: linux/amd64
    command:
      - --redis-addr=redis:6379
    ports:
      - 8080:8080
    depends_on:
      - redis

  jaeger:
    image: jaegertracing/all-in-one:1.63.0
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
