openapi: 3.0.0

info:
  title: Go Backend App
  version: 1.0.0

servers:
  - url: http://localhost:5080

paths:
  /healthz/live:
    $ref: paths/healthzLive.yaml
  /healthz/ready:
    $ref: paths/healthzReady.yaml

components:
  parameters:
    $ref: parameters/_index.yaml
  responses:
    $ref: responses/_index.yaml
  schemas:
    $ref: schemas/_index.yaml
