openapi: 3.0.0
info:
  title: Go Backend App
  version: 1.0.0
servers:
  - url: 'http://localhost:9080'
paths:
  /healthz/live:
    get:
      summary: Returns the current liveness status.
      operationId: getHealthzLive
      security: []
      responses:
        '204':
          description: Successful result.
        '503':
          description: Unhealthy result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        default:
          $ref: '#/components/responses/Error'
  /healthz/ready:
    get:
      summary: Returns the current readiness status.
      operationId: getHealthzReady
      security: []
      responses:
        '204':
          description: Successful result.
        '503':
          description: Unhealthy result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        default:
          $ref: '#/components/responses/Error'
components:
  parameters: {}
  responses:
    Error:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
      required:
        - code
        - message
    HealthStatus:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
        - errors
